/* Generated by Yosys 0.9+2406 (git sha1 334ec5fa, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* src = "c17.v:1.1-14.10" *)
module c17(G1, G16, G17, G2, G3, G4, G5);
  (* src = "c17.v:2.7-2.9" *)
  wire _00_;
  (* src = "c17.v:3.8-3.11" *)
  wire _01_;
  (* src = "c17.v:3.12-3.15" *)
  wire _02_;
  (* src = "c17.v:2.10-2.12" *)
  wire _03_;
  (* src = "c17.v:2.13-2.15" *)
  wire _04_;
  (* src = "c17.v:2.16-2.18" *)
  wire _05_;
  (* src = "c17.v:2.19-2.21" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "c17.v:2.7-2.9" *)
  input G1;
  (* src = "c17.v:3.8-3.11" *)
  output G16;
  (* src = "c17.v:3.12-3.15" *)
  output G17;
  (* src = "c17.v:2.10-2.12" *)
  input G2;
  (* src = "c17.v:2.13-2.15" *)
  input G3;
  (* src = "c17.v:2.16-2.18" *)
  input G4;
  (* src = "c17.v:2.19-2.21" *)
  input G5;
  \$_NOT_  _17_ (
    .A(_04_),
    .Y(_11_)
  );
  \$_NOT_  _18_ (
    .A(_05_),
    .Y(_12_)
  );
  \$_OR_  _19_ (
    .A(_11_),
    .B(_12_),
    .Y(_07_)
  );
  \$_AND_  _20_ (
    .A(_03_),
    .B(_07_),
    .Y(_08_)
  );
  \$_OR_  _21_ (
    .A(_06_),
    .B(_03_),
    .Y(_09_)
  );
  \$_AND_  _22_ (
    .A(_07_),
    .B(_09_),
    .Y(_02_)
  );
  \$_AND_  _23_ (
    .A(_04_),
    .B(_00_),
    .Y(_10_)
  );
  \$_OR_  _24_ (
    .A(_08_),
    .B(_10_),
    .Y(_01_)
  );
  assign _06_ = G5;
  assign G17 = _02_;
  assign _04_ = G3;
  assign _00_ = G1;
  assign _05_ = G4;
  assign _03_ = G2;
  assign G16 = _01_;
endmodule
