/* Generated by Yosys 0.9+2406 (git sha1 334ec5fa, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module s27_bench(blif_clk_net, blif_reset_net, G0, G1, G2, G3, G17);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "s27_behav.v:11.7-11.9" *)
  wire _05_;
  (* src = "s27_behav.v:12.7-12.9" *)
  wire _06_;
  (* src = "s27_behav.v:27.6-27.9" *)
  wire _07_;
  wire _08_,_09_, _10_, _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  input G0, G1;
  wire G10;
  wire G11;
  wire G13;
  output G17;
  input G2;
  input G3;
  wire G5;
  wire G6;
  wire G7;
  input blif_clk_net;
  input blif_reset_net;
  \$_NOT_  _23_ (
    .A(_14_),
    .Y(_16_)
  );
  \$_NOT_  _24_ (
    .A(_12_),
    .Y(_17_)
  );
  \$_NOT_  _25_ (
    .A(_11_),
    .Y(_18_)
  );
  \$_OR_  _26_ (
    .A(_05_),
    .B(_16_),
    .Y(_19_)
  );
  \$_OR_  _27_ (
    .A(_15_),
    .B(_06_),
    .Y(_20_)
  );
  \$_OR_  _28_ (
    .A(_17_),
    .B(_20_),
    .Y(_21_)
  );
  \$_AND_  _29_ (
    .A(_19_),
    .B(_21_),
    .Y(_22_)
  );
  \$_OR_  _30_ (
    .A(_13_),
    .B(_22_),
    .Y(_10_)
  );
  \$_NOT_  _31_ (
    .A(_10_),
    .Y(_08_)
  );
  \$_AND_  _32_ (
    .A(_18_),
    .B(_20_),
    .Y(_09_)
  );
  \$_AND_  _33_ (
    .A(_05_),
    .B(_10_),
    .Y(_07_)
  );
  (* src = "s27_behav.v:38.1-42.15" *)
  \$_DFF_PP0_  G7_reg /* _34_ */ (
    .C(blif_clk_net),
    .D(G13),
    .Q(G7),
    .R(blif_reset_net)
  );
  (* src = "s27_behav.v:33.1-37.15" *)
  \$_DFF_PP0_  G6_reg /* _35_ */ (
    .C(blif_clk_net),
    .D(G11),
    .Q(G6),
    .R(blif_reset_net)
  );
  (* src = "s27_behav.v:28.1-32.15" *)
  \$_DFF_PP0_  G5_reg /* _36_ */ (
    .C(blif_clk_net),
    .D(G10),
    .Q(G5),
    .R(blif_reset_net)
  );
  assign _05_ = G0;
  assign _14_ = G6;
  assign _12_ = G3;
  assign _15_ = G7;
  assign _06_ = G1;
  assign _13_ = G5;
  assign G11 = _08_;
  assign G17 = _10_;
  assign _11_ = G2;
  assign G13 = _09_;
  assign G10 = _07_;
endmodule